/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActionHistoryRouteImport } from './routes/admin.action-history'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminAssignmentsRouteImport } from './routes/admin.assignments'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminHelpRouteImport } from './routes/admin.help'
import { Route as AdminIncidentsRouteImport } from './routes/admin.incidents'
import { Route as AdminLiveMapRouteImport } from './routes/admin.live-map'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPayrollsRouteImport } from './routes/admin.payrolls'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as WorkerDashboardRouteImport } from './routes/worker.dashboard'
import { Route as AdminWorkersIndexRouteImport } from './routes/admin.workers.index'
import { Route as AdminWorkersIdRouteImport } from './routes/admin.workers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActionHistoryRoute = AdminActionHistoryRouteImport.update({
  id: '/admin/action-history',
  path: '/admin/action-history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignmentsRoute = AdminAssignmentsRouteImport.update({
  id: '/admin/assignments',
  path: '/admin/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/admin/help',
  path: '/admin/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: '/admin/incidents',
  path: '/admin/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveMapRoute = AdminLiveMapRouteImport.update({
  id: '/admin/live-map',
  path: '/admin/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/admin/locations',
  path: '/admin/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayrollsRoute = AdminPayrollsRouteImport.update({
  id: '/admin/payrolls',
  path: '/admin/payrolls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerDashboardRoute = WorkerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => WorkerRoute,
} as any)
const AdminWorkersIndexRoute = AdminWorkersIndexRouteImport.update({
  id: '/admin/workers/',
  path: '/admin/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkersIdRoute = AdminWorkersIdRouteImport.update({
  id: '/admin/workers/$id',
  path: '/admin/workers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/action-history': typeof AdminActionHistoryRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/live-map': typeof AdminLiveMapRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payrolls': typeof AdminPayrollsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/workers/$id': typeof AdminWorkersIdRoute
  '/admin/workers/': typeof AdminWorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/action-history': typeof AdminActionHistoryRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/live-map': typeof AdminLiveMapRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payrolls': typeof AdminPayrollsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/admin/workers/$id': typeof AdminWorkersIdRoute
  '/admin/workers': typeof AdminWorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/action-history': typeof AdminActionHistoryRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/assignments': typeof AdminAssignmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/live-map': typeof AdminLiveMapRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payrolls': typeof AdminPayrollsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/worker/dashboard': typeof WorkerDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/workers/$id': typeof AdminWorkersIdRoute
  '/admin/workers/': typeof AdminWorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/setup-password'
    | '/worker'
    | '/admin/action-history'
    | '/admin/approvals'
    | '/admin/assignments'
    | '/admin/attendance'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/help'
    | '/admin/incidents'
    | '/admin/live-map'
    | '/admin/locations'
    | '/admin/notifications'
    | '/admin/payrolls'
    | '/admin/reports'
    | '/admin/settings'
    | '/worker/dashboard'
    | '/admin/'
    | '/admin/workers/$id'
    | '/admin/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/setup-password'
    | '/worker'
    | '/admin/action-history'
    | '/admin/approvals'
    | '/admin/assignments'
    | '/admin/attendance'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/help'
    | '/admin/incidents'
    | '/admin/live-map'
    | '/admin/locations'
    | '/admin/notifications'
    | '/admin/payrolls'
    | '/admin/reports'
    | '/admin/settings'
    | '/worker/dashboard'
    | '/admin'
    | '/admin/workers/$id'
    | '/admin/workers'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/setup-password'
    | '/worker'
    | '/admin/action-history'
    | '/admin/approvals'
    | '/admin/assignments'
    | '/admin/attendance'
    | '/admin/documents'
    | '/admin/finance'
    | '/admin/help'
    | '/admin/incidents'
    | '/admin/live-map'
    | '/admin/locations'
    | '/admin/notifications'
    | '/admin/payrolls'
    | '/admin/reports'
    | '/admin/settings'
    | '/worker/dashboard'
    | '/admin/'
    | '/admin/workers/$id'
    | '/admin/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
  WorkerRoute: typeof WorkerRouteWithChildren
  AdminActionHistoryRoute: typeof AdminActionHistoryRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminAssignmentsRoute: typeof AdminAssignmentsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminIncidentsRoute: typeof AdminIncidentsRoute
  AdminLiveMapRoute: typeof AdminLiveMapRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPayrollsRoute: typeof AdminPayrollsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminWorkersIdRoute: typeof AdminWorkersIdRoute
  AdminWorkersIndexRoute: typeof AdminWorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/action-history': {
      id: '/admin/action-history'
      path: '/admin/action-history'
      fullPath: '/admin/action-history'
      preLoaderRoute: typeof AdminActionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assignments': {
      id: '/admin/assignments'
      path: '/admin/assignments'
      fullPath: '/admin/assignments'
      preLoaderRoute: typeof AdminAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/admin/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/incidents': {
      id: '/admin/incidents'
      path: '/admin/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live-map': {
      id: '/admin/live-map'
      path: '/admin/live-map'
      fullPath: '/admin/live-map'
      preLoaderRoute: typeof AdminLiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/admin/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payrolls': {
      id: '/admin/payrolls'
      path: '/admin/payrolls'
      fullPath: '/admin/payrolls'
      preLoaderRoute: typeof AdminPayrollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/dashboard': {
      id: '/worker/dashboard'
      path: '/dashboard'
      fullPath: '/worker/dashboard'
      preLoaderRoute: typeof WorkerDashboardRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/admin/workers/': {
      id: '/admin/workers/'
      path: '/admin/workers'
      fullPath: '/admin/workers/'
      preLoaderRoute: typeof AdminWorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workers/$id': {
      id: '/admin/workers/$id'
      path: '/admin/workers/$id'
      fullPath: '/admin/workers/$id'
      preLoaderRoute: typeof AdminWorkersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkerRouteChildren {
  WorkerDashboardRoute: typeof WorkerDashboardRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerDashboardRoute: WorkerDashboardRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupPasswordRoute: SetupPasswordRoute,
  WorkerRoute: WorkerRouteWithChildren,
  AdminActionHistoryRoute: AdminActionHistoryRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminAssignmentsRoute: AdminAssignmentsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminLiveMapRoute: AdminLiveMapRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPayrollsRoute: AdminPayrollsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminWorkersIdRoute: AdminWorkersIdRoute,
  AdminWorkersIndexRoute: AdminWorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
